### ISSUE TITLE
No conda env file

### ISSUE THREAD

**Issue by mr-zhangcc** [HodgesGenomicsLab/ATAC-STARR-seq#2]
Hi, this is a nice tool. But I didn't find pkgs.txt and conda_env.yml. Where are they?

**Comment by tyler-hansen** [comment]
Hi, thanks for letting us know! I guess I forgot to include them--I'm very sorry. I cannot recover these files or the information to regenerate them. I did include a list of the packages that we use, so I would install those with conda or, for the R packages, via bioconductor. I removed reference to the conda files in the readme. Again, apologies and thanks for pointing this out!
